# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Tests - AstraMongoose
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up the node version
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
      - name: setup project
        run: |
          npm i
      - name: compile
        run: npm pack
      - name: upload compile artifacts
        uses: actions/upload-artifact@v3
        with:
          name: astra-mongoose-0.0.3.tgz
          path: astra-mongoose-0.0.3.tgz
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up the node version
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
      - name: setup project
        run: |
          npm i
      - name: run tests
        run: npm test
